### PR TITLE
fixed bug when using dependency_injector package

### PR DESCRIPTION
**Pull request by Nibell**

### CODE REVIEW

**Comment by Nibell** [comment]
When using [dependency-injector ](https://github.com/ets-labs/python-dependency-injector), and have injected clients to class, the class hides the self property.
So added __class__ to get base class, and get all properties.
Verified that it works with not injected and injected classes.

**Comment by Nibell** [comment]
@megafetis @svenhartmann Do any of you have time to look at this pr

**Comment by Nibell** [comment]
@megafetis @svenhartmann Can you look on this PR?

**Comment by megafetis** [comment]
Why you dropped python 3.5 support?

**Comment by Nibell** [comment]
> Why you dropped python 3.5 support?

I dropped support for python 3.5, because that has stopped being supported by Python Software Foundation, plus stopped being supported by pytest and twine

**Comment by megafetis** [comment]
Ok I will merge

**Comment by Nibell** [comment]
> Ok I will merge

Hi,
Saw that missed to update _version.py, can you change it to __version__ = '1.3.0' and build a new package to pypi.org?

**Comment by megafetis** [comment]
version is 1.3 now for >=3.6 in pypi org. Thanks

**Pull request merged**
